### ISSUE TITLE
Add Standalone gateway and separate brokers

### ISSUE THREAD

**Issue by salaboy** [zeebe-io/zeebe-cluster-helm#1]
Like here: 
https://github.com/camundacon2019/zeebe-ft-demo/blob/master/docker-compose.yml

**Comment by Zelldon** [comment]
For our deployments/benchmark we will need this as well. 

Here is a configuration we currently use to deploy a standalone gateway:


**Deployment:**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: configuration
          configMap:
            name: gateway
            defaultMode: 0744
      containers:
        - name: gateway
          image: camunda/zeebe:latest
          ports:
            - containerPort: 26500
              name: gateway
            - containerPort: 26502
              name: cluster
            - containerPort: 9600
              name: monitoring
          env:
            - name: ZEEBE_STANDALONE_GATEWAY
              value: "true"
            - name: ZEEBE_GATEWAY_CLUSTER_MEMBER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: configuration
              mountPath: /usr/local/zeebe/conf/log4j2.xml
              subPath: log4j2.xml
          securityContext:
            capabilities:
                add: ["SYS_ADMIN"]
          readinessProbe:
            tcpSocket:
              port: gateway
            initialDelaySeconds: 20
            periodSeconds: 5

```

**Service:**
```
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
    - port: 26500
      name: grpc
    - port: 9600
      name: monitoring
```

Might help to implement this.

**Comment by salaboy** [comment]
@Zelldon @npepinpe @saig0 can you guys point me out how does the standalone gateway connects with the brokers? where is that configuration?

**Comment by salaboy** [comment]
I am currently getting 
```2020-03-10 09:23:23.303 [] [atomix-partition-group-membership-service-0] WARN  io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService - Failed to locate management group via bootstrap nodes. Please ensure partition groups are configured either locally or remotely and the node is able to reach partition group members.``` in the gateway

**Comment by Zelldon** [comment]
Hey @salaboy this is currently expected, we have no fix for that but it should still work

**Comment by salaboy** [comment]
let me try to deploy some processes 
and I will send an initial PR to review

**Comment by salaboy** [comment]
Still not finding the brokers.. there is something that I'm missing.. in the previous deployment descriptor there is a configMap, which seems to only contain the logging config files.. but is there something else require for the gateway to locate the brokers? 
Currently I am running
```
salaboy> zbctl status --insecure                                                               
Cluster size: 0
Partitions count: 0
Replication factor: 0
Brokers:
```

Where no brokers are found, even when the brokers are up and running right besides the gateway.

**Comment by salaboy** [comment]
does this make sense: -> 
```ZEEBE_GATEWAY_CLUSTER_MEMBER_ID:  zeebe-zeebe-gateway-7f565445fd-5jm2h (v1:metadata.name)```

**Comment by salaboy** [comment]
that is basically the name of the pod hosting the gateway.

**Comment by Zelldon** [comment]
@npepinpe i think you setup the last time the standalone gateway any idea? I think in the gateway config the `contactPoint` needs to be set correctly.

**Comment by npepinpe** [comment]
You need to point the contactPoint to at least one of the brokers - this isn't optimal in terms of discoverability obviously, but that's how it is for now. I don't remember having to do anything in particular tbh. 

Having the pod name as the node ID is totally fine, I think that's also what I was doing.

**Comment by npepinpe** [comment]
I additionally configured the following environment vars:

```yaml
            - name: ZEEBE_GATEWAY_CONTACT_POINT
              value: "$(BROKER_SERVICE_NAME)"
            - name: ZEEBE_GATEWAY_HOST
              value: 0.0.0.0
```

where $(BROKER_SERVICE_NAME) was taken from the downstream API as

```yaml
  - name: BROKER_SERVICE_NAME
    objref:
      kind: Service
      name: broker
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
```

This was for the kustomize setup, but should be easy enough to adapt.

**Comment by Zelldon** [comment]
Hey guys I think the current setup doesn't work, at least for me.


I had to disable the standalone and enable the embedded again to get my benchmarks working

```
gatewayMetrics: true
gateway.replicas: 0

env:
  - name: ZEEBE_BROKER_NETWORK_MAXMESSAGESIZE
    value: "256KB"
  - name: ZEEBE_BROKER_DATA_LOGSEGMENTSIZE
    value: "128MB"
  - name: ZEEBE_BROKER_GATEWAY_ENABLE
    value: "true"
```

**Comment by npepinpe** [comment]
Is this fixed by now?

**Comment by ezolnbl** [comment]
anybody experienced a double env var for ZEEBE_BROKER_GATEWAY_ENABLE when defining the helm chart(zeebe 0.0.122) like this: 
```
zeebe-cluster:
  global:
    zeebe: "zeebe-zeebe"
    elasticsearch:
      host: "zeebe-elasticsearch"
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  cpuThreadCount: "2"
  ioThreadCount: "2"
  pvcSize: "10Gi"
  pvcAccessModes: [ "ReadWriteOnce" ]

  resources:
    requests:
      cpu: 100m

  env:
    - name: ZEEBE_BROKER_GATEWAY_ENABLE
      value: "true"

  gateway:
    replicas: 0
    logLevel: warn
    env:
      - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
        value: "4"
```

and in kubectl desribe:
```
 Environment:
   ZEEBE_BROKER_CLUSTER_CLUSTERNAME:                zeebe-zeebe
   ZEEBE_LOG_LEVEL:                                 debug
   ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT:            1
   ZEEBE_BROKER_CLUSTER_CLUSTERSIZE:                1
   ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR:          1
   ZEEBE_BROKER_THREADS_CPUTHREADCOUNT:             2
   ZEEBE_BROKER_THREADS_IOTHREADCOUNT:              2
   ZEEBE_BROKER_GATEWAY_ENABLE:                     false
   ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME:  io.zeebe.exporter.ElasticsearchExporter
   ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL:   http://zeebe-elasticsearch:9200
   ZEEBE_BROKER_NETWORK_COMMANDAPI_PORT:            26501
   ZEEBE_BROKER_NETWORK_INTERNALAPI_PORT:           26502
   ZEEBE_BROKER_NETWORK_MONITORINGAPI_PORT:         9600
   K8S_POD_NAME:                                    zeebe-zeebe-0 (v1:metadata.name)
   JAVA_TOOL_OPTIONS:                               -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:MaxRAMPercentage=25.0 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+PrintFlagsFinal -Xmx4g -Xms4g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/da
-XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
   ZEEBE_BROKER_GATEWAY_ENABLE:                     true
```
and embedded gateway is not started because of this
