### ISSUE TITLE
Expose Elasticsearch configuration

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-helm#10]
Elasticsearch should be configurable (pvc size, max heap)

Currently limits:
```
     Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:      100m
      memory:   2Gi
```

PVC's
```
+ kubectl get pvc
NAME                                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-zeebe-cluster-zeebe-0                    Bound    pvc-7db36228-6bb2-4a59-b6f7-2e87c301a57d   5Gi        RWO            standard       7m25s
data-zeebe-cluster-zeebe-1                    Bound    pvc-2b28f312-7611-4e01-beb6-37c7b665be29   5Gi        RWO            standard       7m25s
data-zeebe-cluster-zeebe-2                    Bound    pvc-ebb712e9-9201-48ac-9879-905f2f19737a   5Gi        RWO            standard       7m25s
elasticsearch-master-elasticsearch-master-0   Bound    pvc-11a4a637-46a5-4956-9cad-8abe5b2135dd   30Gi       RWO            standard       7m25s
elasticsearch-master-elasticsearch-master-1   Bound    pvc-353a97b7-5112-4e21-bc85-6eb158c4c6e2   30Gi       RWO            standard       7m25s
elasticsearch-master-elasticsearch-master-2   Bound    pvc-8cabf9f2-e18e-4ede-b7f2-8deff981a9a2   30Gi       RWO            standard       7m25s
```

What we use in our benchmarks:
```
[zell helm/ ns:zell-helm]$ cat ../setup/elastic-chart-values.yaml 
---
image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
imageTag: 7.5.0

replicas: 3
minimumMasterNodes: 2

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "ssd"
  resources:
    requests:
        storage: 300Gi

esJavaOpts: "-Xmx4g -Xms4g"

resources:
  requests:
    cpu: 3
    memory: 8Gi
  limits:
    cpu: 3
    memory: 8Gi
```
