### ISSUE TITLE
Add an optional service monitor for metrics

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-helm#12]
Would be nice to have an optional service monitor to expose our metrics

```
[zell k8s/ ns:zell-helm]$ cat service-monitor.yaml 
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zeebe-monitor
  labels:
      release: metrics
spec:
  selector:
    matchLabels:
      app: zeebe
  endpoints:
      - honorLabels: true
        port: monitoring
        interval: 10s
```

**Comment by Zelldon** [comment]
```
---
apiVersion: v1
kind: Service
metadata:
  name: zeebe
  labels:
    app: zeebe
spec:
  clusterIP: None
  publishNotReadyAddresses: True
  ports:
    - port: 26500
      name: grpc
    - port: 9600
      name: monitoring
  selector:
    app: zeebe
```
