### ISSUE TITLE
More configuration for the Zeebe statefulset

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-helm#13]
Currently we have several things differently configured for the zeebe statefulset

Example statefulset:
```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeebe
  labels:
    app: zeebe
spec:
  serviceName: "zeebe"
  selector:
    matchLabels:
      app: zeebe
  replicas: 3
  podManagementPolicy: Parallel
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
       accessModes:
         - ReadWriteOnce
       storageClassName: ssd
       resources:
         requests:
           storage: 128Gi
  template:
    metadata:
      labels:
        app: zeebe
    spec:
      volumes:
      - name: configuration
        configMap:
          name: zeebe
          defaultMode: 0744
      containers:
      - name: zeebe
        image: camunda/zeebe:SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 26500
          name: gateway
        - containerPort: 26501
          name: command
        - containerPort: 26502
          name: internal
        - containerPort: 9600
          name: monitoring
        env:
          - name: JAVA_TOOL_OPTIONS
            value: |
              -XX:+PrintFlagsFinal
              -Xmx4g
              -Xms4g
              -XX:+HeapDumpOnOutOfMemoryError
              -XX:HeapDumpPath=/usr/local/zeebe/data
              -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
          - name: ZEEBE_LOG_LEVEL
            value: "debug"
          - name: ATOMIX_LOG_LEVEL
            value: "info"
          - name: ZEEBE_CLUSTER_SIZE
            value: "3"
        resources:
          limits:
            cpu: 5
            memory: 12Gi
          requests:
            cpu: 5
            memory: 12Gi
        volumeMounts:
          - name: data
            mountPath: /usr/local/zeebe/data
          - name: configuration
            mountPath: /usr/local/zeebe/conf/zeebe.cfg.toml
            subPath: zeebe.cfg.toml
        command:
          - "/bin/sh"
          - "-c"
          - "ZEEBE_HOST=$(hostname -f) ZEEBE_CONTACT_POINTS=$(for i in $(seq 0 $((ZEEBE_CLUSTER_SIZE-1))); do echo -n \"zeebe-$i.$(hostname -d):26502,\"; done) ZEEBE_NODE_ID=${HOSTNAME##*-} exec tini -- /usr/local/bin/startup.sh"
        # enable for profiling
        securityContext:
            capabilities:
                add: ["NET_ADMIN", "SYS_ADMIN"]
        readinessProbe:
          httpGet:
              path: /ready
              port: 9600
          initialDelaySeconds: 20
          periodSeconds: 5
```

Important would be the java options, the limits like CPU and Memory but also the PVC size etc.

**Comment by salaboy** [comment]
@Zelldon this is great.. but let's figure out which are the most important and the most frequent parameters that the team changes so we can start with them. 
You mention: 
- [] Java Options
- [] Limits CPU and Memory
- [] PVC size 

Also.. if this is your default configuration, is it sensitive to have these configurations for a default setup of Zeebe? 
If so, I would rather have these configuration values as default for the charts.

**Comment by Zelldon** [comment]
Actually we use them as default yes. After we found the right values, for the pvc for example, we are not changing them so often anymore. But still would be nice to have the possibility to do so.

**Comment by salaboy** [comment]
@Zelldon totally.. I will add the PVC size value.. I am just trying to find which ones to do first that are more valuable for most common situations.

**Comment by salaboy** [comment]
Notice that JavaOptions and CPU and Memory are already supported.. but not documented.. so I am updating the Chart Docs here: https://github.com/zeebe-io/zeebe-cluster-helm

**Comment by Zelldon** [comment]
Cool thanks :+1:

**Comment by salaboy** [comment]
@Zelldon when you have time( probably not now) but can you please share the specs of the cluster that you are using to run the previous specs (plus ElasticSearch). It looks like the configs are quite resource-intensive, which might be fine to run benchmarks and production workloads but for newbie users, it might be quite a lot. 
I tend to think that we should have a set of `values.yaml` files with different profiles. Where one of these files will be the configuration that you shared, but the ones that come by default can be more limited for bootstrapping getting started environments.

**Comment by salaboy** [comment]
@Zelldon ok PVC configs added. I will release the changes later on.. 
I am currently thinking about:  

```
securityContext:
  capabilities:
    add: ["NET_ADMIN", "SYS_ADMIN"]
```

Some weeks ago a community user contributed with the parameterization of `securityContext`
That means that we can have this.. but I wonder if we should have that as default. 
Why do we need that?

**Comment by Zelldon** [comment]
> @Zelldon when you have time( probably not now) but can you please share the specs of the cluster that you are using to run the previous specs (plus ElasticSearch). It looks like the configs are quite resource-intensive, which might be fine to run benchmarks and production workloads but for newbie users, it might be quite a lot.
I tend to think that we should have a set of values.yaml files with different profiles. Where one of these files will be the configuration that you shared, but the ones that come by default can be more limited for bootstrapping getting started environments.

I think it is fine to have per default very limited resources etc. If the user needs more or different value he should be able to configure it.

For example I used your latest release to configure the helm chart like this:


```
[zell helm/ ns:zell-helm]$ cat zeebe-values.yaml 

image:
  repository: camunda/zeebe
  tag: SNAPSHOT
  pullPolicy: IfNotPresent

# ZEEBE CFG

clusterSize: 3
partitionCount: 3
replicationFactor: 3
cpuThreadCount: 4
ioThreadCount: 4

# JavaOpts:
# DEFAULTS

JavaOpts: |
  -XX:+UseParallelGC 
  -XX:MinHeapFreeRatio=5
  -XX:MaxHeapFreeRatio=10
  -XX:MaxRAMPercentage=25.0 
  -XX:GCTimeRatio=4 
  -XX:AdaptiveSizePolicyWeight=90
  -XX:+PrintFlagsFinal
  -Xmx4g
  -Xms4g
  -XX:+HeapDumpOnOutOfMemoryError
  -XX:HeapDumpPath=/usr/local/zeebe/data
  -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log

# RESOURCES

resources:
  limits:
    cpu: 5
    memory: 12Gi
  requests:
    cpu: 5
    memory: 12Gi

# PVC

pvcAccessMode: ["ReadWriteOnce"]
pvcSize: 128Gi
pvcStorageClassName: ssd


# ELASTIC

elasticsearch:
  enabled: true
  imageTag: 6.8.5 

  replicas: 3
  minimumMasterNodes: 2

  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "ssd"
    resources:
      requests:
          storage: 300Gi

  esJavaOpts: "-Xmx4g -Xms4g"

  resources:
    requests:
      cpu: 3
      memory: 8Gi
    limits:
      cpu: 3
      memory: 8Gi

# KIBANA

kibana:
  enabled: false

# PROMETHEUS

prometheus:
  enabled: false
```

I think it is fine for now. Thank you very much for your work!
