### ISSUE TITLE
Add possibility to configure security context

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-helm#17]
In our benchmarks we need to add capabilities like:

```
securityContext:
  capabilities:
    add: ["NET_ADMIN", "SYS_ADMIN"]
```

See discussion in https://github.com/zeebe-io/zeebe-cluster-helm/issues/13#issuecomment-576181028

**Comment by salaboy** [comment]
I think that this is supported already.. but not the default .. did you give it a try ?

**Comment by Zelldon** [comment]
I tried it with:

```
# SECURITY CONTEXT
# Used for profiling and network adjustments
podSecurityContext:
  capabilities:
    add: ["NET_ADMIN", "SYS_ADMIN"]

```

And:
```
securityContext:
  capabilities:
    add: ["NET_ADMIN", "SYS_ADMIN"]
```

But unfortunately both didn't work. 

Expected capabilities:

```
CapInh:	00000000a82435fb
CapPrm:	00000000a82435fb
CapEff:	00000000a82435fb
CapBnd:	00000000a82435fb
```

How to find them:

```
kubectl exec -it zeebe-cluster-zeebe-0 bash
$ cd /proc/1
$ cat status
```

With both settings I got:

```
CapInh:	00000000a80425fb
CapPrm:	00000000a80425fb
CapEff:	00000000a80425fb
CapBnd:	00000000a80425fb
```

Related K8's documentation and example https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container
