### ISSUE TITLE
`ServiceMonitor` is not optional

### ISSUE THREAD

**Issue by Hermsi1337** [zeebe-io/zeebe-cluster-helm#21]
Hey Folks,

first of all - many thanks for the work and effort you put in `zeebe`.  
This piece of software is performing really well in our environment.

I've noticed, that there is a new `manifest` called `service-monitor.yaml` which requires the deployment of an additional operator and the corresponding `CRD`s.

In our case, that specific manifest prohibits a deployment of the latest `zeebe-cluster`-chart.  
Even though the `prometheus-operator` of `CoreOS` is a pretty great solution, we should make  the templating of it's `ServiceMonitor` optional for this `zeebe-cluster`-chart.  

What do you think of adding a simple `if` around here...

```yaml
{{- if .Values.prometheusOperator.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zeebe-monitor
  labels:
      release: metrics
spec:
  selector:
    matchLabels:
      app: zeebe
  endpoints:
      - honorLabels: true
        port: http
        interval: 10s
{{- end }}
```
