### ISSUE TITLE
Fix StatefulSet spec

### ISSUE THREAD

**Issue by phoenixwp** [zeebe-io/zeebe-cluster-helm#26]
Deploying the chart the following error appear:
```
# helm install -nvzeebe --namespace default zeebe-cluster
Error: release wms-zeebe failed: StatefulSet in version "v1" cannot be handled as a StatefulSet: v1.StatefulSet.Spec: v1.StatefulSetSpec.VolumeClaimTemplates: []v1.PersistentVolumeClaim: v1.PersistentVolumeClaim.Spec: v1.PersistentVolumeClaimSpec.AccessModes: []v1.PersistentVolumeAccessMode: decode slice: expect [ or n, but found ", error found in #10 byte of ...|ssModes":"ReadWriteO|..., bigger context ...|"metadata":{"name":"data"},"spec":{"accessModes":"ReadWriteOnce","resources":{"requests":{"storage":|...
```

Issue is in statefulset spec in **accessModes** definition.
Original:
```
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: {{ .Values.pvcAccessModes }}
      storageClassName: {{ .Values.pvcStorageClassName }}
      resources:
        requests:
          storage: {{ .Values.pvcSize | quote }}
```

Should be:
```
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - {{ .Values.pvcAccessModes }}
      storageClassName: {{ .Values.pvcStorageClassName }}
      resources:
        requests:
          storage: {{ .Values.pvcSize | quote }}
```
