### ISSUE TITLE
Confusing different prometheus settings

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-helm#27]
The prometheus operator can be enabled via `prometheusOperator.enabled`

https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/requirements.yaml#L13

To just enable the prometheus servicemonitor we have to use `prometheus.servicemonitor.enabled`

https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/templates/service-monitor.yaml#L1

I think it would less confusing or easier to use if we have the structure like:

```yaml
prometheus:
 operator:
  enabled: false
 servicemonitor:
  enabled: false
```

Instead of:

```
prometheus:
  servicemonitor:
    enabled: false

prometheusOperator:
  enabled: false
```
