### ISSUE TITLE
Error defining extra init containers

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe-cluster-helm#30]
When adding extra init containers, we ran into issue where the resulting YAML was badly indented. Our quickfix was to switch from `indent 8` to `nindent 8`, as it seems `indent 8`  print out the template directly with the current indentation + 8 for the first line, whereas nindent would first go to a new line and add 8.

So given this values:

```yaml
extraInitContainers: |
  - name: verfiy
    image: gcr.io/zeebe-io/zb-log-check:0.1.0
    imagePullPolicy: Always
    args: ["/work-dir"]
    volumeMounts:
    - name: data
      mountPath: "/work-dir/data"
```

The resulting YAML looked like this:

```yaml
initContainers:
                - name: verfiy
        image: gcr.io/zeebe-io/zb-log-check:0.1.0
        imagePullPolicy: Always
        args: ["/work-dir"]
        volumeMounts:
           - name: data
             mountPath: "/work-dir/data"
```
