### ISSUE TITLE
Configure port names via values.yaml to support Istio Port Selection

### ISSUE THREAD

**Issue by andylholloway** [zeebe-io/zeebe-cluster-helm#37]
Hi
I recently deployed Zeebe to a kubernetes cluster that uses the Istio Service Mesh. 

To configure Port Selection (https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/) the port names should be prefixed with the protocol e.g. grpc-gateway.

At the moment I am pulling down the helm chart, expanding the charts and modifying the port names. 

Could the port names be configurable via the values.yaml file?

Example:
Service.yaml
```
    - port: {{ .Values.service.http.port }}
      protocol: TCP
      name: http   # change to {{ .Values.service.http.name }}
    - port: {{ .Values.service.gateway.port }}
      protocol: TCP
      name: gateway  # change to {{ .Values.service.gateway.name }}
```

Statefulset.yaml
```
ports:
        - containerPort: 9600
          name: http    # change to {{ .Values.service.http.name }}
        - containerPort: 26500
          name: gateway  # change to {{ .Values.service.gateway.name }}
        - containerPort: 26501
          name: command  # change to {{ .Values.service.command.name }}
        - containerPort: 26502
          name: internal  # change to {{ .Values.service.internal.name }}
```
values.yaml
```
service:
  type: ClusterIP
  http:
    port: 9600
    name: http-web
  gateway:
    port: 26500
    name: grpc-gateway
  command:
    port: 26501
    name: tcp-command
  internal:
    port: 26502
    name: tcp-internal
```
Thanks
Andy
