### ISSUE TITLE
Allow specifying additional environment variables to brokers

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe-cluster-helm#44]
When testing or developing Zeebe, it's quite useful to be able to pass arbitrary environment variables to broker deployments in order to verify the impact of various settings.

One way of doing so, as done in the Prometheus chart, could be by defining an `env` value, which is takes in the standard, raw YAML format for k8s, e.g.:

```yaml
env:
  - name: ATOMIX_LOG_LEVEL
    value: debug
  - name: ZEEBE_GATEWAY_MONITORING_ENABLED
    value: "true"
```
