### ISSUE TITLE
Gateway deployment readiness probe tcp socket port is hard coded.

### ISSUE THREAD

**Issue by andylholloway** [zeebe-io/zeebe-cluster-helm#51]
Hi 
I'm currently trying to deploy the latest zeebe-cluster-helm chart (0.0.88) to Kubernetes, which uses Istio with port selection: https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/.

I changed the gateway port name to "grpc-gateway" in the values file e.g.
```
serviceGatewayName: grpc-gateway
```
But the change broke the gateway pod. After a little investigation I noticed that the gateway-deployment.yaml `readinessProbe.tcpSocket.port` is hard coded to "gateway" e.g.

```
 readinessProbe:
            tcpSocket:
              port: gateway
            initialDelaySeconds: 20
            periodSeconds: 5
```

I have downloaded the helm chart and changed the readinessProbe to:
```
readinessProbe:
            tcpSocket:
              port: {{ default "gateway" .Values.serviceGatewayName  }}
            initialDelaySeconds: 20
            periodSeconds: 5
```
This seems to have fixed the issue, by allowing the gateway pod to become ready. 

Are you happy for me to issue this change as a PR?

Thanks
Andy
