### ISSUE TITLE
Multiple gateways fails to reach brokers. 

### ISSUE THREAD

**Issue by pradeeepst** [zeebe-io/zeebe-cluster-helm#64]
Openshift version: 3.11
Helm version: 3
Zeebe version: 0.22.1
How to reproduce ? 
 Deploy helm chart with 3 replicas of gateway and broker. Broker pod results in below error. 
`2020-05-11 06:09:30.301 [] [atomix-partition-group-membership-service-0] WARN  io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService - Failed to locate management group via bootstrap nodes. Please ensure partition groups are configured either locally or remotely and the node is able to reach partition group members`

But it works ok when deployed with 1 replica of gateway and 3 replica of broker. No config change.

**Comment by Zelldon** [comment]
This log is not an issue. Yes it is confusing it is removed in the newest versions, but it is not a problem. Do you have problems to reach the brokers with more then one gateway ?

**Comment by pradeeepst** [comment]
Yes, couldnt reach brokers if the gateway is more than one.

**Comment by Zelldon** [comment]
Thanks for conforming. We need to have a look maybe we have some questions later.

**Comment by Zelldon** [comment]
Can't reproduce this issue with the our current snapshot version.
I run our normal test benchmark with three gateways and it seem to work.

![multi-gw](https://user-images.githubusercontent.com/2758593/81639562-95b6c600-941c-11ea-8808-75ebeee6c01f.png)

I used the following configuration:

```yaml
image:
  repository: camunda/zeebe
  tag: SNAPSHOT
  pullPolicy: Always

# ZEEBE CFG
clusterSize: 3
partitionCount: 3
replicationFactor: 3
cpuThreadCount: 4
ioThreadCount: 4
gatewayMetrics: true

gateway:
  replicas: 3
  logLevel: debug

# Uncomment to add custom YAML configuration
# This will overwrite anything at the application.yml location
# zeebeCfg: {}

# JavaOpts:
# DEFAULTS
JavaOpts: >
  -XX:+UseParallelGC 
  -XX:MinHeapFreeRatio=5
  -XX:MaxHeapFreeRatio=10
  -XX:MaxRAMPercentage=25.0 
  -XX:GCTimeRatio=4 
  -XX:AdaptiveSizePolicyWeight=90
  -XX:+PrintFlagsFinal
  -Xmx4g
  -Xms4g
  -XX:+ExitOnOutOfMemoryError
  -XX:+HeapDumpOnOutOfMemoryError
  -XX:HeapDumpPath=/usr/local/zeebe/data
  -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log

# Environment variables
env:
  # Enable JSON logging for google cloud stackdriver
  - name: ZEEBE_LOG_APPENDER
    value: Stackdriver
  - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
    value: "true"

# RESOURCES
resources:
  limits:
    cpu: 5
    memory: 12Gi
  requests:
    cpu: 5
    memory: 12Gi

# PVC
pvcAccessMode: ["ReadWriteOnce"]
pvcSize: 128Gi
pvcStorageClassName: ssd


# ELASTIC
elasticsearch:
  enabled: true
  imageTag: 6.8.5

  replicas: 3
  minimumMasterNodes: 2

  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "ssd"
    resources:
      requests:
        storage: 300Gi

  esJavaOpts: "-Xmx4g -Xms4g"

  resources:
    requests:
      cpu: 3
      memory: 8Gi
    limits:
      cpu: 3
      memory: 8Gi

# KIBANA
kibana:
  enabled: false

# PROMETHEUS
prometheus:
  enabled: false

  servicemonitor:
    enabled: true
```

What is the reason to use 0.22.1 instead of 0.23.1?
