### ISSUE TITLE
gateway config doesn't work with ipv6 only network

### ISSUE THREAD

**Issue by neermitt** [zeebe-io/zeebe-cluster-helm#83]
Looks like chart doesn't work with ipv6 only network

Following environment variables, hardcoded bind to "0.0.0.0" which doesn't work with ipv6 only network
- ZEEBE_GATEWAY_NETWORK_HOST
- ZEEBE_GATEWAY_MONITORING_HOST

**Comment by npepinpe** [comment]
You can set the environment variables via the chart values, e.g.:

```yaml
gateway:
  env:
    - name: ZEEBE_GATEWAY_NETWORK_HOST
      value: "::/0"
```

You can also do the same for the broker:

```yaml
env:
  - name: ZEEBE_BROKER_NETWORK_HOST
    value: "::/0"
```

Please confirm if this works or not for you :+1:
